#!/usr/bin/env bash

################################################################################
#                                Configurations                                #
################################################################################

# Transmission rpc address with authentication disabled
tr_api='http://localhost:9091/transmission/rpc'

# Directory storing seeding files, match "download-dir" in transmission settings
seed_dir='/volume2/@transmission'

# Directory where transmission monitors for new torrents, match "watch-dir" in
# transmission settings, leave empty to disable watch_dir cleanup
watch_dir='/volume1/video/Torrent'

# Disk quota (minimum free space to keep on disk)
((GiB = 1024 ** 3, quota = 50 * GiB))

# Download save locations
declare -A locations=(
  ['default']='/volume1/homes/admin/Download'
  ['av']='/volume1/driver/Temp'
  ['film']='/volume1/video/Film'
  ['tv']='/volume1/video/TV'
  ['music']='/volume1/music/Download'
)
